USE LOGIN

CREATE TABLE TBL_USER(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOMBRES NVARCHAR(100) NOT NULL,
APELLIDOS NVARCHAR(100) NOT NULL,
USERNAME NVARCHAR(100) NOT NULL,
PASSWOR NVARCHAR(100) NOT NULL
);

SELECT *FROM TBL_USER
drop table TBL_USER;
INSERT INTO TBL_USER (NOMBRES,APELLIDOS,USERNAME, PASSWOR) VALUES ('NELSON DANIEL','RAMOS GARCIA','NELSON', '4033');
INSERT INTO TBL_USER(NOMBRES,APELLIDOS,USERNAME,PASSWOR) VALUES ('ALVARO LEONEL','RAMOS GARCIA','Alvaro','4792');

delete from TBL_USER;